/*AST abstruct syntacs tree get a line from the parser and brakes it to the basic componantes.
*/

/*This function will get a line from the parser and brakes it to the basic componantes.*/

#include <stdlib.h>
#include <string.h>
#include "globals.h"
#include "table_generator.h"
#include "util.h"
#include "machine_code.h"
#include "data_structures.h"

/*Deffing the types of the commands*/
typedef enum op_codes{
    MOV=0,
    CMP=1,
    ADD=2,
    SUB=3,
    NOT=4,
    CLR=5,
    LEA=6,
    INC=7,
    DEC=8,
    JMP=9,
    BNE=10,
    RED=11,
    PRN=12,
    JSR=13,
    RTS=14,
    STOP=15
    } op_code;

/*Deffing the types of the registers*/
typedef enum registers{
    R0=0,
    R1=1,
    R2=2,
    R3=3,
    R4=4,
    R5=5,
    R6=6,
    R7=7,
    NOT_REG = -1
    } _register;

/*Deffing the types of the addressing methods*/
typedef enum addressing_methods{
    IMMEDIATE=1,
    DIRECT=3,
    REGISTER = 5
    } addressing_method;

/*Deffing the incoding methods)*/
typedef enum incoding_methods{
    ABSOLUTE=0,
    EXTERNAL=1,
    RELOCATABLE=2
    } incoding_method;



/*
**************************************************
---------DEFINING THE 12 BIT WORDS TYPES----------
FOR COMMANDS 
|   11-9   |   8-5  |   4-2 |   1-0     |
|   DEST   |    OP  |   SRC |   A,R,E   |

FOR DATA
|   11-7   |    6-2      |   1-0     |
|   DEST   |    SRC     |   A,R,E   |
**************************************************
*/


/*Define data word*/
typedef struct data_word{
    unsigned int ARE:2;
    unsigned int data:10;
    } data_word;

/*Define register word*/
typedef struct register_word{
    unsigned int ARE:2;
    unsigned int dest_reg:5;
    unsigned int source_reg:5;
    } register_word;

/*Define immediate direct word*/
typedef struct immediate_direct_word{
    unsigned int ARE:2;
    unsigned int operand:10;
    } immediate_direct_word;


/*Define guidance word*/


/*Define data word a word generated by an guidance command as 
as apoosed to a word generated by an instruction command*/
typedef struct guidance_word{
    char *guidance_op;
    union guidance_word_type{
        symbol *symbol;
        data_word *data;
    } guidance_word_type;
    } guidance_word;

/*Deffing an instruction word*/
typedef struct instrction_word{

    unsigned int ARE:2;
    unsigned int dest_add:3;
    unsigned int op_code:4;
    unsigned int source_add:3;
    word *dest_operand;
    word *source_operand;
    } instruction_word;

/*Deffing a word*/
typedef struct word{
    char *label;
    union word_type{
        data_word *data_word;
        register_word *register_word;
        immediate_direct_word *immediate_direct_word;
        instruction_word *instruction_word;
        } word_type;
    char *error;
    } word;

/*Deffing libe in the code*/
typedef struct assembly_lines{
    char *file_name;
    int line_number;
    char *content;
} line;

/*
################### THE CONCRETE SYNTAX #######################
ast-exp:= {lable* , line-exp, error-exp}
line-exp:= {instruction-exp | guidance-exp}
instruction-exp:= {op-code-exp+, ARE-exp, reemaing-words}
guidance-exp:= {guidance-op-exp ,data-exp+ ,ARE-exp}
op-code-exp:= {op_code , rand-exp*}
rand-exp:= {{register | immediate-direct-exp | data-word-exp},{ARE-exp}}
val-exp:= {add-exp | oprnd-exp}
add-exp:= {register-exp | immediate-direct-exp | data-word-exp}
oprnd-exp:= {register | symbol-exp | immediate-val-exp}
register:= {R0 | R1 | R2 | R3 | R4 | R5 | R6 | R7 | NOT_REG}
symbol-exp:= {label, value}
value:= {number}
immediate-val-exp:= {data-word-exp}
remaining-words:= {char*}
guidance-op-exp:= {.string | .data | .entry | .extern}
ARE-exp:= {A | R | E}
*/



typedef struct ast{
    char *label;
    line *line_exp;
    char *error;
} ast;

typedef struct line{
    union line_type{
        instrction_word *instrction_exp;
        guidance_word *guidance_line;
    } line_type;
    char *error;
} line;





ast *line_to_ast(char *line, long line_number);

word *ast_to_word(ast *line);






*/
