/*AST abstruct syntacs tree get a line from the parser and brakes it to the basic componantes.
*/

/*This function will get a line from the parser and brakes it to the basic componantes.*/

#include <stdlib.h>
#include <string.h>
#include "globals.h"
#include "table_generator.h"
#include "util.h"
#include "machine_code.h"
#include "data_structures.h"

/*Deffing the types of the commands*/
typedef enum op_codes{
    MOV=0,
    CMP=1,
    ADD=2,
    SUB=3,
    NOT=4,
    CLR=5,
    LEA=6,
    INC=7,
    DEC=8,
    JMP=9,
    BNE=10,
    RED=11,
    PRN=12,
    JSR=13,
    RTS=14,
    STOP=15
    } op_code;

typedef enum guid_op{
    data=0,
    string=1,
    entry=2,
    extern_guid_op=3
}guid_op;

/*Deffing the types of the registers*/
typedef enum registers{
    R0=0,
    R1=1,
    R2=2,
    R3=3,
    R4=4,
    R5=5,
    R6=6,
    R7=7,
    NOT_REG = -1
    } _register;

/*Deffing the types of the addressing methods*/
typedef enum addressing_methods{
    IMMEDIATE=1,
    DIRECT=3,
    REGISTER = 5
    } addressing_method;

/*Deffing the incoding methods)*/
typedef enum incoding_methods{
    ABSOLUTE=0,
    EXTERNAL=1,
    RELOCATABLE=2
    } incoding_method;

/*
**************************************************
---------DEFINING THE 12 BIT WORDS TYPES----------
FOR COMMANDS 
|   11-9   |   8-5  |   4-2 |   1-0     |
|   DEST   |    OP  |   SRC |   A,R,E   |

FOR DATA
|   11-7   |    6-2      |   1-0     |
|   DEST   |    SRC     |   A,R,E   |
**************************************************
*/
/*Define data word*/
typedef struct data_word{
    unsigned int data:12;
    } data_word;

/*Define register word*/
typedef struct register_word{
    unsigned int ARE:2;
    unsigned int dest_reg:5;
    unsigned int source_reg:5;
    } register_word;

/*Define immediate direct word*/
typedef struct immediate_direct_word{
    unsigned int ARE:2;
    unsigned int operand:10;
    } immediate_direct_word;

/*Define guidance word*/

/*Define data word a word generated by an guidance command as 
as apoosed to a word generated by an instruction command*/
typedef struct guidance_word{
    char *guidance_op;
    char *args;
    } guidance_word;

/*Deffing an instruction word*/
typedef struct instruction_word{
    unsigned int ARE:2;
    unsigned int dest_add:3;
    unsigned int op_code:4;
    unsigned int source_add:3;
    } instruction_word;

typedef struct word{
    union *word_type{
        data_word *data_word;
        register_word *register_word;
        immediate_direct_word *immediate_direct_word;
        instruction_word *instruction_word;
        guidance_word *guidance_word;
        } word_type;
    char *error;
    } word;

/*Deffing a word*/
typedef struct ast_line{
    char *label;
    word *word[3];
    char *error;
    } ast_line;


/*
################### THE CONCRETE SYNTAX #######################
ast-exp:= {lable* , line-exp, error-exp}
line-exp:= {instruction-exp | guidance-exp}
instruction-exp:= {op-code-exp+, ARE-exp, reemaing-words}
guidance-exp:= {guidance-op-exp ,data-exp+ ,ARE-exp}
op-code-exp:= {op_code , rand-exp*}
rand-exp:= {{register | immediate-direct-exp | data-word-exp},{ARE-exp}}
val-exp:= {add-exp | oprnd-exp}
add-exp:= {register-exp | immediate-direct-exp | data-word-exp}
oprnd-exp:= {register | symbol-exp | immediate-val-exp}
register:= {R0 | R1 | R2 | R3 | R4 | R5 | R6 | R7 | NOT_REG}
symbol-exp:= {label, value}
value:= {number}
immediate-val-exp:= {data-word-exp}
remaining-words:= {char*}
guidance-op-exp:= {.string | .data | .entry | .extern}
ARE-exp:= {A | R | E}
*/


typedef struct line{
    union line_type{
        instruction_word *instruction_exp;
        guidance_word *guidance_line;
    } line_type;
    char *error;
} line;

/*
ast_line *line_to_ast(char *line, long line_number);

list *line_to_list(char *line, long line_number);

ast_line *ast_to_word(char *line);
*/

/*This part will contain function designed for checking legality and set error if needed*/
bool is_label(char *first_frase);
bool ligal_label(char *first_frase);
ast_line *build_ast(char *current_line,symbol_list *symbol_table,long *data_counter,long *instruction_counter,char *error_msg,char *tmp_lable ,data_word *data_image[], instruction_word *instruction_image[]);
bool is_guidance_of_label(char *frase);




void set_ligal_params(int *ins_code, int *ligal_add_source, int *ligal_add_dest, int *word_limit);


